version: '3.8'

services:
  db:
    image: postgres:alpine3.18
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
    volumes:
      - ./pg:/var/lib/postgresql/data